add(application): 내 원서 추가
themoment-team/hellogsm-server-v3 pull request #25
Opened 2024-06-11 05:43 UTC by tlsgmltjd

## 개요

졸업 예정자, 졸업자, 검정고시의 지원자가 원서를 추가하는 기능을 개발하였습니다.

## 본문

- `/application/v3/application/me` 경로로 원서에 대한 정보를 요청하여 지원자의 졸업상태에 따라 각각의 `AbstractApplication`, `AbstractMiddleSchoolGrade`, `AbstractPersonalInformation`의 상속 관계의 엔티티가 저장됩니다.
- `@NotSpace` 문자열에 공백을 허용하지 않는 커스텀 어노테이션 입니다. 전화번호, 학교이름 등의 dto 필드에 사용됩니다. 
`@ValidDesiredMajors` 1, 2, 3지망 희망 전공을 입력할 때 중복된 전공을 입력하진 않았는지 , null은 아닌지 검증하는 커스텀 어노테이션 입니다.
- 

## 변경사항 및 추가사항
* 검정고시, 졸업자의 엔티티에서 생성시 PK를 받는 필드가 `@NonNull` 어노테이션이 붙어있어 생성시 유효성 검사 예외가 발생하여 해당 두 엔티티의 생성자에 대한 `@NonNull`  어노테이션을 삭제하였습니다.
* `AbstractMiddleSchoolGrade` 엔티티 생성시 JSON 값을 파싱하여 점수를 환산하는 로직은 작성하지 않고 두었습니다. 추후에 해당 로직 작성이 필요해보입니다.

2024-06-12 01:32 UTC, jangwooooo requested changes

2024-06-12 01:32 UTC, jangwooooo commented on src/main/java/team/themoment/hellogsmv3/domain/application/service/CreateApplicationService.java
> +                .orElseThrow(() -> new ExpectedException("존재하지 않는 유저입니다.", HttpStatus.NOT_FOUND));
이거 `AuthenticatedUserManager`에서 가져오는 값이 `authenticationId`라서 쿼리문 바꾸셔야 할 거 같아요.
변수명도 헷갈리지 않게 바꾸는게 좋을 거 같네요.

2024-06-12 02:18 UTC, jangwooooo requested changes

2024-06-12 02:18 UTC, jangwooooo commented on src/main/java/team/themoment/hellogsmv3/domain/application/service/CreateApplicationService.java
> +                        .competencyEvaluationResult(null)
지금 `screening`이 어디에도 저장되고 있지 않은 것 같습니다.
해당 `EvaluationResult` 클래스안의 `preScreeningEvaluation`필드에 저장해야 될 것 같네요.

2024-06-12 14:22 UTC, tlsgmltjd commented on src/main/java/team/themoment/hellogsmv3/domain/application/service/CreateApplicationService.java
> +                .orElseThrow(() -> new ExpectedException("존재하지 않는 유저입니다.", HttpStatus.NOT_FOUND));
aa939c02f065fc24b1a4864e98599b425974b3bf

네네 확인 감사합니다.. 해당 부분을 햇갈려서 다른 PR에서도 위와 같이 구현하고 있었는데 모두 수정하도록 하겠습니다!

2024-06-12 14:30 UTC, tlsgmltjd commented on src/main/java/team/themoment/hellogsmv3/domain/application/service/CreateApplicationService.java
> +                        .competencyEvaluationResult(null)
7377965d77bee4923a631fab003c72a7e9781165

넵 `EvaluationResult`를 초기화하여 저장하였습니다. 수정 로직에서도 적용하도록 하겠습니다.

2024-06-15 07:59 UTC, jangwooooo reviewed
수고하셨습니다

2024-06-15 07:59 UTC, jangwooooo commented on src/main/java/team/themoment/hellogsmv3/domain/application/dto/request/ApplicationReqDto.java
> +        GraduationStatus graduation,
DTO에 붙여도 어떤 효과가 있나요?

2024-06-15 07:59 UTC, jangwooooo commented on src/main/java/team/themoment/hellogsmv3/domain/application/service/CreateApplicationService.java
> +                .orElseThrow(() -> new ExpectedException("존재하지 않는 유저입니다.", HttpStatus.NOT_FOUND));
메세지에 `authenticationId`정보를 담으면 예외발생시 대응하기 쉬울 것 같아요.

2024-06-15 07:59 UTC, jangwooooo commented on src/main/java/team/themoment/hellogsmv3/domain/application/service/CreateApplicationService.java
> +                                .preScreeningEvaluation(null)
pre에는 null이 아니라 screening을 저장해 주셔야 해요.
지금 어느 곳에서도 screening이 저장되지 않고 있는 거로 보여요.

Candidate, Graduate, Ged 모두 수정부탁드려요.

2024-06-15 07:59 UTC, jangwooooo commented on src/main/java/team/themoment/hellogsmv3/domain/application/service/CreateApplicationService.java
> +                                .evaluationStatus(null).build())
이거 `EvaluationStatus`에 `NOT_YET` 추가하는 건 작은 작업이니깐 해당 브랜치에서 추가하시고 `NOT_YET`으로 초기화하도록 수정하는 게 좋아 보여요.

Candidate, Graduate, Ged 1차2차 모두 다 수정부탁드려요

2024-06-16 14:11 UTC, tlsgmltjd commented on src/main/java/team/themoment/hellogsmv3/domain/application/dto/request/ApplicationReqDto.java
> +        GraduationStatus graduation,
68b0472564fe7c134f206aa178f5d4e9c379fd71

불필요한것 같습니다. 제거하였습니다.

2024-06-16 14:11 UTC, tlsgmltjd commented on src/main/java/team/themoment/hellogsmv3/domain/application/service/CreateApplicationService.java
> +                .orElseThrow(() -> new ExpectedException("존재하지 않는 유저입니다.", HttpStatus.NOT_FOUND));
e927a176e3bc1abb05d3e79c5bd253b2ed9dbf84

예외 메시지에 id를 추가하였습니다.

2024-06-16 14:12 UTC, tlsgmltjd commented on src/main/java/team/themoment/hellogsmv3/domain/application/service/CreateApplicationService.java
> +                                .preScreeningEvaluation(null)
642ac3494b9ef4de5a818d46d5f3b83ff8cd126b

네네 놓치고 있었네요 확인 감사드립니다. 반영하였습니다!

2024-06-16 14:12 UTC, tlsgmltjd commented on src/main/java/team/themoment/hellogsmv3/domain/application/service/CreateApplicationService.java
> +                                .evaluationStatus(null).build())
77a144055c17468cc3780b8028213c08ff34703e

넵 해당 필드를 추가하고 반영하였습니다!

2024-06-17 00:25 UTC, jangwooooo approved these changes

2024-06-17 01:48 UTC, hajeu approved these changes

2024-06-17 01:54 UTC, merged